#
#  Squelette Docker-compose.yml pour le projet Le Bon Sandwich
#  documentation et utilisation de l'image canals/php sur
#  https://gitlab.univ-lorraine.fr/canals5/docker-php
#

version: '3'
networks:
  lbs.net:
    driver: bridge
services:
  #####################################################
  # API SERVICES
  #####################################################

  #######################################
  ###  Service  commande : prise de commandes et suivi des commandes
  ###  api api.commande
  ###  database gérée par le service mysql.commande (sql)
  ###  requêtes HTTP vers api.catalogue et api.fidelisation
  #######################################

  # service api.commande : api frontoffice pour la prise des commandes
  #
  api.commande:
    image: 'canals/php:latest'
    environment:
      - VHOST_HOSTNAME=api.commande.local
      - VHOST_DOCROOT=/var/www/public
    ports:
      - '19080:80'
      - '19043:443'
    volumes:
      - './lbs_commande_service/public:/var/www/public'
      - './lbs_commande_service/src:/var/www/src'
    working_dir: /var/www/src
    networks:
      - lbs.net
    depends_on:
      - mysql.commande

  # service api.suivi.fabrication : api backoffice pour le suivi de fabrication
  # des commandes
  api.suivi.fabrication:
    image: 'canals/php:latest'
    environment:
      - VHOST_HOSTNAME=api.fabrication.local
      - VHOST_DOCROOT=/var/www/pub
    ports:
      - '19680:80'
      - '19643:443'
    volumes:
      - './lbs_fabrication_service/pub:/var/www/pub'
      - './lbs_fabrication_service/src:/var/www/src'
      - './lbs_fabrication_service/log:/var/log/app'
    working_dir: /var/www/src
    networks:
      - lbs.net
    depends_on:
      - mysql.commande
  
  # service api.auth.local : api backoffice pour l'authentification
  api.auth.local:
    image: 'canals/php:latest'
    environment:
      - VHOST_HOSTNAME=api.auth.local
      - VHOST_DOCROOT=/var/www/public
    ports:
      - '19580:80'
      - '19543:443'
    volumes:
      - './lbs_auth_service/pub:/var/www/public'
      - './lbs_auth_service/src:/var/www/src'
      - './lbs_auth_service/log:/var/log/api'
    working_dir: /var/www/src
    networks:
      - lbs.net
    depends_on:
      - mysql.auth

  # service api.backoffice.local : api backoffice pour rediriger les requêtes
  # vers les bons services
  api.backoffice.local:
    image: 'canals/php:latest'
    environment:
      - VHOST_HOSTNAME=api.backoffice.local
      - VHOST_DOCROOT=/var/www/public
    ports:
      - '19480:80'
      - '19443:443'
    volumes:
      - './lbs_backoffice_service/public:/var/www/public'
      - './lbs_backoffice_service/src:/var/www/src'
      - './lbs_backoffice_service/log:/var/log/api'
    working_dir: /var/www/src
    networks:
      - lbs.net
    depends_on:
      - api.auth.local
      - api.suivi.fabrication

  # service sql pour le stockage des commandes -
  # utilisé par l'api  commande et l'api suivi de fabrication
  mysql.commande:
    image: 'mariadb:latest'
    command: '--default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci'
    environment:
      - MYSQL_ROOT_PASSWORD=comroot
      - MYSQL_USER=command_lbs
      - MYSQL_PASSWORD=command_lbs
      - MYSQL_DATABASE=command_lbs
    ports:
      - '3307:3306'
    networks:
      - lbs.net
    volumes:
      - './lbs_commande_service/sql:/var/sql'

  # service sql pour l'authentification
  # utilisé par l'api authentification
  mysql.auth:
    image: 'mariadb:latest'
    command: '--default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci'
    environment:
      - MYSQL_ROOT_PASSWORD=comroot
      - MYSQL_USER=auth_lbs
      - MYSQL_PASSWORD=auth_lbs
      - MYSQL_DATABASE=auth_lbs
    ports:
      - '3407:3306'
    networks:
      - lbs.net
    volumes:
      - './lbs_auth_service/sql:/var/sql'

  # service administration des bases sql
  adminer:
    image: adminer
    ports:
      - '8080:8080'
    networks:
      - lbs.net
  
  ###########################################################
  #   Service catalogue, réalisé avec le CMS Headless Directus
  #   Service SQL géré par postgres
  ###########################################################

  mysql.catalogue:
    image: 'mariadb:latest'
    command: '--default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci'
    environment:
      - MYSQL_ROOT_PASSWORD=comroot
      - MYSQL_USER=catalogue_lbs
      - MYSQL_PASSWORD=catalogue_lbs
      - MYSQL_DATABASE=catalogue_lbs
    ports:
      - '3207:3306'
    networks:
      - lbs.net
    volumes:
      - './lbs_catalogue_service/sql:/var/sql'

  api.catalogue:
    image: directus/directus:latest
    ports:
      - 19055:8055
    volumes:
      - ./lbs_catalogue_service/uploads:/directus/uploads
      - ./lbs_catalogue_service/extensions:/directus/extensions
    networks:
      lbs.net:
        aliases:
          - api.catalogue.local
    depends_on:
      - mysql.catalogue
    environment:
      KEY: '255d861b-5ea1-5996-9aa3-922530ec40b1'
      SECRET: '6116487b-cda1-52c2-b5b5-c8022c45e263'

      DB_CLIENT: 'mysql'
      DB_HOST: 'mysql.catalogue'
      DB_PORT: '3306'
      DB_DATABASE: 'catalogue_lbs'
      DB_USER: 'catalogue_lbs'
      DB_PASSWORD: 'catalogue_lbs'

      CACHE_ENABLED: 'false'
      ADMIN_EMAIL: 'admin@catalogue.net'
      ADMIN_PASSWORD: 'catalogue'